[package]
name = "ainew"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = { version = "^0.12" }
tokio = { version = "^1", features = ["rt-multi-thread", "signal"] }
dotenv = { version = "^0.15" }
